# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024 Tobias Hienzsch

version = 1

[[annotations]]
path = [
    "benchmarks/pffdtd_benchmarks.csv",
    "doc/screenshot.png",
    "src/model_viewer/doc/screenshot.png",
    "src/ruby_SU/RoomExporter.rbz",
]
SPDX-FileCopyrightText = "2021 Brian Hamilton"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "data/models/CTK_Church/CTK_Church_SU2017.skp",
    "data/models/CTK_Church/model_export.json",
    "data/models/CTK_Church/receivers.csv",
    "data/models/CTK_Church/sources.csv",
    "data/models/Musikverein_ConcertHall/Musikverein_SU2017.skp",
    "data/models/Musikverein_ConcertHall/model_export.json",
    "data/models/Musikverein_ConcertHall/receivers.csv",
    "data/models/Musikverein_ConcertHall/sources.csv",
]
SPDX-FileCopyrightText = "2021 Brian Hamilton"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "cmake/profile/linux_sycl",
    "cmake/profile/windows_sycl",
    "data/materials/*.h5",
    "data/models/**/*.obj",
    "data/models/InfiniteBaffle/model.json",
    "data/models/LivingRoom/model.json",
    "data/models/Localization/model.json",
    "data/models/Modes/model.json",
    "data/models/ProStudio/model.json",
    "data/models/Studio/model.json",
]
SPDX-FileCopyrightText = "2024 Tobias Hienzsch"
SPDX-License-Identifier = "MIT"
