# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024 Tobias Hienzsch

version = 1

[[annotations]]
path = ["benchmarks/pffdtd_benchmarks.csv", "doc/screenshot.png"]
SPDX-FileCopyrightText = "2021 Brian Hamilton"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "models/CTK_Church/CTK_Church_SU2017.skp",
    "models/CTK_Church/model_export.json",
    "models/CTK_Church/receivers.csv",
    "models/CTK_Church/sources.csv",
    "models/Musikverein_ConcertHall/Musikverein_SU2017.skp",
    "models/Musikverein_ConcertHall/model_export.json",
    "models/Musikverein_ConcertHall/receivers.csv",
    "models/Musikverein_ConcertHall/sources.csv",
]
SPDX-FileCopyrightText = "2021 Brian Hamilton"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "cmake/profile/linux_sycl",
    "cmake/profile/windows_sycl",
    "models/Diffusor3D/model.json",
    "models/InfiniteBaffle/model.json",
    "models/LivingRoom/model.json",
    "models/Localization/model.json",
    "models/Modes/model.json",
    "models/ProStudio/model.json",
    "models/Studio/model.json",
    "models/**/*.obj",
]
SPDX-FileCopyrightText = "2024 Tobias Hienzsch"
SPDX-License-Identifier = "MIT"
