name: Build

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_PREFIX_PATH: ${{ matrix.cmake_prefix_path }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.osx_target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
            osx_target: ""
            cmake_prefix_path: "/opt/intel/oneapi/tbb/latest"
            cmake_flags: ""
            cxx_flags: "-march=x86-64-v2"
            python_version: "3.12"

          - name: macOS-X64
            os: macos-13
            osx_target: "10.15"
            cmake_prefix_path: ""
            cmake_flags: '-D OpenMP_ROOT=`brew list libomp | grep libomp.a | sed -E "s/\/lib\/.*//"`'
            cxx_flags: "-march=x86-64-v2"
            python_version: "3.12"

          - name: macOS-ARM64
            os: macos-14
            osx_target: "11.0"
            cmake_prefix_path: ""
            cmake_flags: '-D OpenMP_ROOT=`brew list libomp | grep libomp.a | sed -E "s/\/lib\/.*//"`'
            cxx_flags: ""
            python_version: "3.12"

          - name: Windows
            os: windows-latest
            osx_target: ""
            cmake_flags: ""
            cxx_flags: "-march=x86-64-v2"
            python_version: "3.12"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update -y
          sudo apt install -y libomp-dev ninja-build
          pip3 install --break-system-packages conan

      - name: Install TBB (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt update -y
          sudo apt install -y intel-oneapi-tbb-devel

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install conan hdf5 libomp llvm ninja opencv tbb

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install ninja
          pip3 install --upgrade conan

      - name: Install clang
        if: runner.os != 'macOS'
        uses: egor-tensin/setup-clang@v1

      - name: Setup conan
        run: |
          conan profile detect -f
          git clone https://github.com/conan-io/cmake-conan.git -b develop2 external/cmake-conan

      - name: CMake configure
        if: runner.os != 'Windows'
        run: >
          cmake
          -B build
          -G Ninja
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=external/cmake-conan/conan_provider.cmake
          ${{ matrix.cmake_flags }}

      - name: CMake build
        if: runner.os != 'Windows'
        run: cmake --build build

      - name: PIP
        run: pip3 install --verbose .[test]

      - name: Pytest
        run: pytest --cov=pffdtd --cov-branch

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
